export const GET_PRODUCTS_DONE = 'GET_PRODUCTS_DONE';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

export const GET_PRODUCT_DONE = 'GET_PRODUCT_DONE';
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED';;
