export const GET_PRODUCTS_REQUESTED = 'GET_PRODUCTS_REQUESTED';
export const GET_PRODUCTS_INIT_DONE = 'GET_PRODUCTS_INIT_DONE';
export const GET_PRODUCTS_MORE_DONE = 'GET_PRODUCTS_MORE_DONE';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

export const GET_PRODUCT_REQUESTED = 'GET_PRODUCT_REQUESTED';
export const GET_PRODUCT_DONE = 'GET_PRODUCT_DONE';
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED';;
